import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";

dotenv.config();
console.error("AI.ts loaded with API key:", process.env.GEMINI_API_KEY ? "Present" : "Missing");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function summarizeNews(title: string, content: string): Promise<string> {
  if (!process.env.GEMINI_API_KEY) return content.slice(0, 200) + "...";
  
  const models = ["gemini-2.5-flash-lite", "gemini-2.0-flash-lite-preview-02-05", "gemini-2.5-flash", "gemini-1.5-flash"];
  for (const modelName of models) {
    try {
      const currentModel = genAI.getGenerativeModel({ model: modelName });
      const prompt = `Summarize this AI news article in 2-3 concise sentences for a professional dashboard.
      Title: ${title}
      Content: ${content}`;
      
      const result = await currentModel.generateContent(prompt);
      const response = await result.response;
      return response.text();
    } catch (error: any) {
      continue;
    }
  }
  return content.slice(0, 200) + "...";
}

export async function generateLinkedInCaption(title: string, summary: string, url: string): Promise<string> {
  const models = ["gemini-2.5-flash-lite", "gemini-2.0-flash-lite-preview-02-05", "gemini-2.5-flash", "gemini-1.5-flash"];
  
  if (process.env.GEMINI_API_KEY) {
    for (const modelName of models) {
      try {
        const currentModel = genAI.getGenerativeModel({ model: modelName });
        const prompt = `Create an engaging LinkedIn post caption for this AI news. Include relevant hashtags and a call to action.
        Title: ${title}
        Summary: ${summary}
        URL: ${url}`;
        
        const result = await currentModel.generateContent(prompt);
        const response = await result.response;
        const text = response.text();
        if (text) return text;
      } catch (error) {
        continue;
      }
    }
  }
  
  return `🚀 New AI Insight: ${title}\n\n${summary?.slice(0, 150)}...\n\nRead more: ${url}\n\n#AI #ArtificialIntelligence #TechNews`;
}

export async function generateNewsletter(items: {title: string, summary: string, url: string}[]): Promise<string> {
  if (items.length === 0) return "No favorites to include in the newsletter. Go add some AI news!";
  
  const models = ["gemini-2.5-flash-lite", "gemini-2.0-flash-lite-preview-02-05", "gemini-2.5-flash", "gemini-1.5-flash"];
  
  if (process.env.GEMINI_API_KEY) {
    for (const modelName of models) {
      try {
        const currentModel = genAI.getGenerativeModel({ model: modelName });
        const prompt = `Create a professional 'AI Weekly' newsletter summary based on these ${items.length} news items. 
        Format it with clear headings, bullet points, and a professional tone.
        Items: ${JSON.stringify(items)}`;
        
        console.error(`Attempting newsletter with model: ${modelName}`);
        const result = await currentModel.generateContent(prompt);
        const response = await result.response;
        const text = response.text();
        if (text) {
          console.error(`Success with model: ${modelName}`);
          return text;
        }
      } catch (error: any) {
        console.error(`Failed with model ${modelName}:`, error.message || error);
        continue;
      }
    }
  }

  // Fallback Newsletter (Manual Generation) if AI fails or API key is missing
  console.error("Using manual fallback for newsletter generation");
  let newsletter = "# AI Weekly Newsletter\n\nHere are your curated AI updates for the week:\n\n";
  items.forEach((item, index) => {
    newsletter += `### ${index + 1}. ${item.title}\n`;
    newsletter += `${item.summary || "No summary available."}\n`;
    newsletter += `[Read more](${item.url})\n\n`;
  });
  newsletter += "---\n*Generated by AI News Dashboard*";
  return newsletter;
}
